-- MySQL Script generated by MySQL Workbench
-- 10/29/15 17:05:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema P3Database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema P3Database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `P3Database` DEFAULT CHARACTER SET utf8 ;
USE `P3Database` ;

-- -----------------------------------------------------
-- Table `P3Database`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `P3Database`.`Address` (
  `IDAddress` INT NOT NULL,
  `StreetName` VARCHAR(50) NULL,
  `HouseNumber` VARCHAR(15) NULL,
  `AreaCode` INT NULL,
  `Lat` DECIMAL(15) NULL,
  `Lng` DECIMAL(15) NULL,
  PRIMARY KEY (`IDAddress`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `P3Database`.`PropertyInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `P3Database`.`PropertyInfo` (
  `IDPropertyInfo` INT NOT NULL,
  `PropertyType` VARCHAR(45) NULL,
  `NumberOfRooms` INT NULL,
  `YearBuilt` INT NULL,
  PRIMARY KEY (`IDPropertyInfo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `P3Database`.`SalesInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `P3Database`.`SalesInfo` (
  `IDSalesInfo` INT NOT NULL,
  `SalesType` VARCHAR(45) NULL,
  `Price` INT NULL,
  `PriceSqr` INT NULL,
  `SalesDate` DATETIME NULL,
  PRIMARY KEY (`IDSalesInfo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `P3Database`.`Listings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `P3Database`.`Listings` (
  `IDListings` INT NOT NULL,
  `Address` INT NULL,
  `PropertyInfo` INT NULL,
  `SalesInfo` INT NULL,
  PRIMARY KEY (`IDListings`),
  INDEX `Address_idx` (`Address` ASC),
  UNIQUE INDEX `Address_UNIQUE` (`Address` ASC),
  UNIQUE INDEX `PropertyInfo_UNIQUE` (`PropertyInfo` ASC),
  UNIQUE INDEX `SalesInfo_UNIQUE` (`SalesInfo` ASC),
  CONSTRAINT `Address`
    FOREIGN KEY (`Address`)
    REFERENCES `P3Database`.`Address` (`IDAddress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PropertyInfo`
    FOREIGN KEY (`PropertyInfo`)
    REFERENCES `P3Database`.`PropertyInfo` (`IDPropertyInfo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `SalesInfo`
    FOREIGN KEY (`SalesInfo`)
    REFERENCES `P3Database`.`SalesInfo` (`IDSalesInfo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `P3Database` ;

-- -----------------------------------------------------
-- Placeholder table for view `P3Database`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `P3Database`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `P3Database`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `P3Database`.`view1`;
USE `P3Database`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
